version: '3.7'

services:
  db:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - './postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf'
      - /data/db:/data/db
    command: 'postgres -c config_file=/usr/local/etc/postgres/postgres.conf'
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8081:80'
    links:
      - 'db:pgsql-server'
