name: Test core-api

on:
  push:
    branches: [ci-test]
    paths:
      - 'apps/core-api/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGINSERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Check Docker Version
        run: docker --version
      - name: Install Latest Docker
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce
      - name: Check Docker Version
        run: docker --version

      - name: Build image
        run: docker build . -f api.Dockerfile -t ${{ secrets.ACR_LOGINSERVER }}/my-api:latest

      - name: Deploy image
        run: docker push ${{ secrets.ACR_LOGINSERVER }}/my-api:latest
          
          
