name: Test core-api

on:
  push:
    branches: [master]
    paths:
      - 'apps/core-api/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGINSERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - run: |
          docker build . -f api.Dockerfile -t ${{ secrets.ACR_LOGINSERVER }}/my-api:latest
          docker push ${{ secrets.ACR_LOGINSERVER }}/my-api:latest
