name: Test core-api

on:
  push:
    branches: [ci-test]
    paths:
      - 'apps/core-api/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGINSERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build image
        run: docker build --no-cache . -f api.Dockerfile -t ${{ secrets.ACR_LOGINSERVER }}/my-api:latest

      - name: Deploy image
        run: docker push ${{ secrets.ACR_LOGINSERVER }}/my-api:latest
